In [6]:
import pandas as pd
import json
from typing import Tuple
from collections import defaultdict

In [59]:
df_movies = pd.read_csv('tmdb_5000_movies.csv', parse_dates=["release_date"])
df_movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [30]:
# select which columns that contains json strings
json_columns = ["genres", "production_companies", "production_countries", "spoken_languages", "keywords"]
for col in json_columns:
    df_movies[col] = df_movies[col].apply(json.loads)
df_movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.avatarmovie.com/,19995,"[{'id': 1463, 'name': 'culture clash'}, {'id':...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{'name': 'Ingenious Film Partners', 'id': 289...","[{'iso_3166_1': 'US', 'name': 'United States o...",2009-12-10,2787965087,162.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://disney.go.com/disneypictures/pirates/,285,"[{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...","[{'iso_3166_1': 'US', 'name': 'United States o...",2007-05-19,961000000,169.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{'id': 470, 'name': 'spy'}, {'id': 818, 'name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{'name': 'Columbia Pictures', 'id': 5}, {'nam...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2015-10-26,880674609,148.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://www.thedarkknightrises.com/,49026,"[{'id': 849, 'name': 'dc comics'}, {'id': 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{'name': 'Legendary Pictures', 'id': 923}, {'...","[{'iso_3166_1': 'US', 'name': 'United States o...",2012-07-16,1084939099,165.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://movies.disney.com/john-carter,49529,"[{'id': 818, 'name': 'based on novel'}, {'id':...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2012-03-07,284139100,132.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [31]:
df_movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   datetime64[ns]
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: datetime64[ns](1), float64(3), int64(4), object(12)
memory usage: 750.6+ KB

In [33]:
from collections import defaultdict

json_tables = defaultdict(list)


for index, row in df_movies.iterrows():
    for c in json_columns:
        json_tables[c].extend(row[c])

    #     print(c)
    #     print(row[c])

        # for item in row[c]:
        #     name = item.get("name")
        #     if name:
        #         command = f'''
        #         MERGE (n:{c.replace("_", "")} {{name: "{name}"}})
        #         MERGE (m:Movie {{id: {row["id"]}}})
        #         MERGE (m)-[:HAS_{c.replace("_", "").upper()}]->(n)
        #         '''
        #         cypher_commands.append(command)
    # break

for key, items in json_tables.items():
    print(f"{key}: {len(items)} items")

genres: 12160 items
production_companies: 13677 items
production_countries: 6436 items
spoken_languages: 6937 items
keywords: 36194 items

In [44]:
df_movies.loc[1, json_columns]

genres                  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...
production_companies    [{'name': 'Walt Disney Pictures', 'id': 2}, {'...
production_countries    [{'iso_3166_1': 'US', 'name': 'United States o...
spoken_languages                 [{'iso_639_1': 'en', 'name': 'English'}]
keywords                [{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...
Name: 1, dtype: object

In [45]:
json_dfs = {}
for key, items in json_tables.items():
    json_dfs[key] = pd.DataFrame(items).drop_duplicates().reset_index(drop=True)
    print(f"{key}: {json_dfs[key].shape}")
    display(json_dfs[key].head())

genres: (20, 2)

    id             name
0   28           Action
1   12        Adventure
2   14          Fantasy
3  878  Science Fiction
4   80            Crime

production_companies: (5047, 2)

                                     name   id
0                 Ingenious Film Partners  289
1  Twentieth Century Fox Film Corporation  306
2                      Dune Entertainment  444
3                Lightstorm Entertainment  574
4                    Walt Disney Pictures    2

production_countries: (88, 2)

  iso_3166_1                      name
0         US  United States of America
1         GB            United Kingdom
2         JM                   Jamaica
3         BS                   Bahamas
4         DM                  Dominica

spoken_languages: (87, 2)

  iso_639_1      name
0        en   English
1        es   Español
2        fr  Français
3        it  Italiano
4        de   Deutsch

keywords: (9813, 2)

     id           name
0  1463  culture clash
1  2964         future
2  3386      space war
3  3388   space colony
4  3679        society

In [50]:
a = df_movies.head(1)["genres"].values[0]

In [51]:
a

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [11]:
df_movies.isnull().sum()

budget                     0
genres                     0
homepage                3091
id                         0
keywords                   0
original_language          0
original_title             0
overview                   3
popularity                 0
production_companies       0
production_countries       0
release_date               1
revenue                    0
runtime                    2
spoken_languages           0
status                     0
tagline                  844
title                      0
vote_average               0
vote_count                 0
dtype: int64

In [28]:
df_movies["status"].value_counts()

status
Released           4795
Rumored               5
Post Production       3
Name: count, dtype: int64

In [53]:
m1 = df_movies.iloc[0,:].to_dict()
m1

{'budget': 237000000,
 'genres': [{'id': 28, 'name': 'Action'},
  {'id': 12, 'name': 'Adventure'},
  {'id': 14, 'name': 'Fantasy'},
  {'id': 878, 'name': 'Science Fiction'}],
 'homepage': 'http://www.avatarmovie.com/',
 'id': 19995,
 'keywords': [{'id': 1463, 'name': 'culture clash'},
  {'id': 2964, 'name': 'future'},
  {'id': 3386, 'name': 'space war'},
  {'id': 3388, 'name': 'space colony'},
  {'id': 3679, 'name': 'society'},
  {'id': 3801, 'name': 'space travel'},
  {'id': 9685, 'name': 'futuristic'},
  {'id': 9840, 'name': 'romance'},
  {'id': 9882, 'name': 'space'},
  {'id': 9951, 'name': 'alien'},
  {'id': 10148, 'name': 'tribe'},
  {'id': 10158, 'name': 'alien planet'},
  {'id': 10987, 'name': 'cgi'},
  {'id': 11399, 'name': 'marine'},
  {'id': 13065, 'name': 'soldier'},
  {'id': 14643, 'name': 'battle'},
  {'id': 14720, 'name': 'love affair'},
  {'id': 165431, 'name': 'anti war'},
  {'id': 193554, 'name': 'power relations'},
  {'id': 206690, 'name': 'mind and soul'},
  {'id': 209714, 'name': '3d'}],
 'original_language': 'en',
 'original_title': 'Avatar',
 'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
 'popularity': 150.437577,
 'production_companies': [{'name': 'Ingenious Film Partners', 'id': 289},
  {'name': 'Twentieth Century Fox Film Corporation', 'id': 306},
  {'name': 'Dune Entertainment', 'id': 444},
  {'name': 'Lightstorm Entertainment', 'id': 574}],
 'production_countries': [{'iso_3166_1': 'US',
   'name': 'United States of America'},
  {'iso_3166_1': 'GB', 'name': 'United Kingdom'}],
 'release_date': Timestamp('2009-12-10 00:00:00'),
 'revenue': 2787965087,
 'runtime': 162.0,
 'spoken_languages': [{'iso_639_1': 'en', 'name': 'English'},
  {'iso_639_1': 'es', 'name': 'Español'}],
 'status': 'Released',
 'tagline': 'Enter the World of Pandora.',
 'title': 'Avatar',
 'vote_average': 7.2,
 'vote_count': 11800}

In [65]:
[c for c in m1 if not isinstance(m1[c], list)]

['budget',
 'homepage',
 'id',
 'original_language',
 'original_title',
 'overview',
 'popularity',
 'release_date',
 'revenue',
 'runtime',
 'status',
 'tagline',
 'title',
 'vote_average',
 'vote_count']

In [ ]:
from neo4j import GraphDatabase

# URI examples: "neo4j://localhost", "neo4j+s://xxx.databases.neo4j.io"
URI = ""
AUTH = ("", "")

with GraphDatabase.driver(URI, auth=AUTH) as driver:
    driver.verify_connectivity()

def run_query(query, parameters=None):
    with GraphDatabase.driver(URI, auth=AUTH) as driver:
        with driver.session() as session:
            result = session.run(query, parameters)
            return result.data()

In [ ]:
query = """
MERGE (m:Movie {id: $id})
ON CREATE SET 
    m.title = $title,
    m.homepage = $homepage,
    m.budget = $budget,
    m.popularity = $popularity,
    m.original_language = $original_language,
    m.overview = $overview,
    m.original_title = $original_title,
    m.release_date = $release_date,
    m.revenue = $revenue,
    m.status = $status,
    m.tagline = $tagline,
    m.vote_average = $vote_average,
    m.vote_count = $vote_count

WITH m, $genres AS genres
UNWIND genres AS g
    MERGE (genre:Genre {id: g.id})
    ON CREATE SET genre.name = g.name
    MERGE (m)-[:HAS_GENRE]->(genre)

WITH m, $production_companies AS production_companies
UNWIND production_companies AS pc
    MERGE (company:Company {id: pc.id})
    ON CREATE SET company.name = pc.name
    MERGE (m)-[:PRODUCED_BY]->(company)

WITH m, $production_countries AS production_countries
UNWIND production_countries AS pco
    MERGE (country:ProductionCountry {iso_3166_1: pco.iso_3166_1})
    ON CREATE SET country.name = pco.name
    MERGE (m)-[:PRODUCED_IN]->(country)

WITH m, $spoken_languages AS spoken_languages
UNWIND spoken_languages AS sl
    MERGE (language:Language {iso_639_1: sl.iso_639_1})
    ON CREATE SET language.name = sl.name
    MERGE (m)-[:SPOKEN_IN]->(language)

WITH m, $keywords AS keywords
UNWIND keywords AS kw
    MERGE (keyword:Keyword {id: kw.id})
    ON CREATE SET keyword.name = kw.name
    MERGE (m)-[:HAS_KEYWORD]->(keyword)

RETURN m
"""

In [67]:
run_query(query, m1)

[{'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,

In [30]:
df_credits = pd.read_csv('tmdb_5000_credits.csv')
df_credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [58]:
# find columns that contain json strings



def parse_json_columns(frame) -> Tuple[pd.DataFrame, list]:
    frame = frame.copy()
    json_col = [col for col in frame.columns if frame[col].apply(lambda x: isinstance(x, str) and x.startswith('[') and x.endswith(']')).all()]
    if not json_col:
        print("No JSON columns found.")
    for col in json_col:
        frame[col] = frame[col].apply(json.loads)
    return frame, json_col

df_credits, json_columns = parse_json_columns(df_credits)
print(f"JSON columns: {json_columns}")
df_credits.head()

No JSON columns found.
JSON columns: []

,movie_id,title,cast,crew
0,19995,Avatar,"[{'cast_id': 242, 'character': 'Jake Sully', '...","[{'credit_id': '52fe48009251416c750aca23', 'de..."
1,285,Pirates of the Caribbean: At World's End,"[{'cast_id': 4, 'character': 'Captain Jack Spa...","[{'credit_id': '52fe4232c3a36847f800b579', 'de..."
2,206647,Spectre,"[{'cast_id': 1, 'character': 'James Bond', 'cr...","[{'credit_id': '54805967c3a36829b5002c41', 'de..."
3,49026,The Dark Knight Rises,"[{'cast_id': 2, 'character': 'Bruce Wayne / Ba...","[{'credit_id': '52fe4781c3a36847f81398c3', 'de..."
4,49529,John Carter,"[{'cast_id': 5, 'character': 'John Carter', 'c...","[{'credit_id': '52fe479ac3a36847f813eaa3', 'de..."

In [61]:
df, json_columns = parse_json_columns(df_movies)
print(f"JSON columns: {json_columns}")
df.head()

JSON columns: ['genres', 'keywords', 'production_companies', 'production_countries', 'spoken_languages']

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.avatarmovie.com/,19995,"[{'id': 1463, 'name': 'culture clash'}, {'id':...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{'name': 'Ingenious Film Partners', 'id': 289...","[{'iso_3166_1': 'US', 'name': 'United States o...",2009-12-10,2787965087,162.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",http://disney.go.com/disneypictures/pirates/,285,"[{'id': 270, 'name': 'ocean'}, {'id': 726, 'na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{'name': 'Walt Disney Pictures', 'id': 2}, {'...","[{'iso_3166_1': 'US', 'name': 'United States o...",2007-05-19,961000000,169.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{'id': 470, 'name': 'spy'}, {'id': 818, 'name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{'name': 'Columbia Pictures', 'id': 5}, {'nam...","[{'iso_3166_1': 'GB', 'name': 'United Kingdom'...",2015-10-26,880674609,148.0,"[{'iso_639_1': 'fr', 'name': 'Français'}, {'is...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://www.thedarkknightrises.com/,49026,"[{'id': 849, 'name': 'dc comics'}, {'id': 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{'name': 'Legendary Pictures', 'id': 923}, {'...","[{'iso_3166_1': 'US', 'name': 'United States o...",2012-07-16,1084939099,165.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://movies.disney.com/john-carter,49529,"[{'id': 818, 'name': 'based on novel'}, {'id':...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{'name': 'Walt Disney Pictures', 'id': 2}]","[{'iso_3166_1': 'US', 'name': 'United States o...",2012-03-07,284139100,132.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [47]:
c1 = df_credits.loc[0, :].to_dict()
c1

{'movie_id': 19995,
 'title': 'Avatar',
 'cast': [{'cast_id': 242,
   'character': 'Jake Sully',
   'credit_id': '5602a8a7c3a3685532001c9a',
   'gender': 2,
   'id': 65731,
   'name': 'Sam Worthington',
   'order': 0},
  {'cast_id': 3,
   'character': 'Neytiri',
   'credit_id': '52fe48009251416c750ac9cb',
   'gender': 1,
   'id': 8691,
   'name': 'Zoe Saldana',
   'order': 1},
  {'cast_id': 25,
   'character': 'Dr. Grace Augustine',
   'credit_id': '52fe48009251416c750aca39',
   'gender': 1,
   'id': 10205,
   'name': 'Sigourney Weaver',
   'order': 2},
  {'cast_id': 4,
   'character': 'Col. Quaritch',
   'credit_id': '52fe48009251416c750ac9cf',
   'gender': 2,
   'id': 32747,
   'name': 'Stephen Lang',
   'order': 3},
  {'cast_id': 5,
   'character': 'Trudy Chacon',
   'credit_id': '52fe48009251416c750ac9d3',
   'gender': 1,
   'id': 17647,
   'name': 'Michelle Rodriguez',
   'order': 4},
  {'cast_id': 8,
   'character': 'Selfridge',
   'credit_id': '52fe48009251416c750ac9e1',
   'gender': 2,
   'id': 1771,
   'name': 'Giovanni Ribisi',
   'order': 5},
  {'cast_id': 7,
   'character': 'Norm Spellman',
   'credit_id': '52fe48009251416c750ac9dd',
   'gender': 2,
   'id': 59231,
   'name': 'Joel David Moore',
   'order': 6},
  {'cast_id': 9,
   'character': 'Moat',
   'credit_id': '52fe48009251416c750ac9e5',
   'gender': 1,
   'id': 30485,
   'name': 'CCH Pounder',
   'order': 7},
  {'cast_id': 11,
   'character': 'Eytukan',
   'credit_id': '52fe48009251416c750ac9ed',
   'gender': 2,
   'id': 15853,
   'name': 'Wes Studi',
   'order': 8},
  {'cast_id': 10,
   'character': "Tsu'Tey",
   'credit_id': '52fe48009251416c750ac9e9',
   'gender': 2,
   'id': 10964,
   'name': 'Laz Alonso',
   'order': 9},
  {'cast_id': 12,
   'character': 'Dr. Max Patel',
   'credit_id': '52fe48009251416c750ac9f1',
   'gender': 2,
   'id': 95697,
   'name': 'Dileep Rao',
   'order': 10},
  {'cast_id': 13,
   'character': 'Lyle Wainfleet',
   'credit_id': '52fe48009251416c750ac9f5',
   'gender': 2,
   'id': 98215,
   'name': 'Matt Gerald',
   'order': 11},
  {'cast_id': 32,
   'character': 'Private Fike',
   'credit_id': '52fe48009251416c750aca5b',
   'gender': 2,
   'id': 154153,
   'name': 'Sean Anthony Moran',
   'order': 12},
  {'cast_id': 33,
   'character': 'Cryo Vault Med Tech',
   'credit_id': '52fe48009251416c750aca5f',
   'gender': 2,
   'id': 397312,
   'name': 'Jason Whyte',
   'order': 13},
  {'cast_id': 34,
   'character': 'Venture Star Crew Chief',
   'credit_id': '52fe48009251416c750aca63',
   'gender': 2,
   'id': 42317,
   'name': 'Scott Lawrence',
   'order': 14},
  {'cast_id': 35,
   'character': 'Lock Up Trooper',
   'credit_id': '52fe48009251416c750aca67',
   'gender': 2,
   'id': 986734,
   'name': 'Kelly Kilgour',
   'order': 15},
  {'cast_id': 36,
   'character': 'Shuttle Pilot',
   'credit_id': '52fe48009251416c750aca6b',
   'gender': 0,
   'id': 1207227,
   'name': 'James Patrick Pitt',
   'order': 16},
  {'cast_id': 37,
   'character': 'Shuttle Co-Pilot',
   'credit_id': '52fe48009251416c750aca6f',
   'gender': 0,
   'id': 1180936,
   'name': 'Sean Patrick Murphy',
   'order': 17},
  {'cast_id': 38,
   'character': 'Shuttle Crew Chief',
   'credit_id': '52fe48009251416c750aca73',
   'gender': 2,
   'id': 1019578,
   'name': 'Peter Dillon',
   'order': 18},
  {'cast_id': 39,
   'character': 'Tractor Operator / Troupe',
   'credit_id': '52fe48009251416c750aca77',
   'gender': 0,
   'id': 91443,
   'name': 'Kevin Dorman',
   'order': 19},
  {'cast_id': 40,
   'character': 'Dragon Gunship Pilot',
   'credit_id': '52fe48009251416c750aca7b',
   'gender': 2,
   'id': 173391,
   'name': 'Kelson Henderson',
   'order': 20},
  {'cast_id': 41,
   'character': 'Dragon Gunship Gunner',
   'credit_id': '52fe48009251416c750aca7f',
   'gender': 0,
   'id': 1207236,
   'name': 'David Van Horn',
   'order': 21},
  {'cast_id': 42,
   'character': 'Dragon Gunship Navigator',
   'credit_id': '52fe48009251416c750aca83',
   'gender': 0,
   'id': 215913,
   'name': 'Jacob Tomuri',
   'order': 22},
  {'cast_id': 43,
   'character': 'Suit #1',
   'credit_id': '52fe48009251416c750aca87',
   'gender': 0,
   'id': 143206,
   'name': 'Michael Blain-Rozgay',
   'order': 23},
  {'cast_id': 44,
   'character': 'Suit #2',
   'credit_id': '52fe48009251416c750aca8b',
   'gender': 2,
   'id': 169676,
   'name': 'Jon Curry',
   'order': 24},
  {'cast_id': 46,
   'character': 'Ambient Room Tech',
   'credit_id': '52fe48009251416c750aca8f',
   'gender': 0,
   'id': 1048610,
   'name': 'Luke Hawker',
   'order': 25},
  {'cast_id': 47,
   'character': 'Ambient Room Tech / Troupe',
   'credit_id': '52fe48009251416c750aca93',
   'gender': 0,
   'id': 42288,
   'name': 'Woody Schultz',
   'order': 26},
  {'cast_id': 48,
   'character': 'Horse Clan Leader',
   'credit_id': '52fe48009251416c750aca97',
   'gender': 2,
   'id': 68278,
   'name': 'Peter Mensah',
   'order': 27},
  {'cast_id': 49,
   'character': 'Link Room Tech',
   'credit_id': '52fe48009251416c750aca9b',
   'gender': 0,
   'id': 1207247,
   'name': 'Sonia Yee',
   'order': 28},
  {'cast_id': 50,
   'character': 'Basketball Avatar / Troupe',
   'credit_id': '52fe48009251416c750aca9f',
   'gender': 1,
   'id': 1207248,
   'name': 'Jahnel Curfman',
   'order': 29},
  {'cast_id': 51,
   'character': 'Basketball Avatar',
   'credit_id': '52fe48009251416c750acaa3',
   'gender': 0,
   'id': 89714,
   'name': 'Ilram Choi',
   'order': 30},
  {'cast_id': 52,
   'character': "Na'vi Child",
   'credit_id': '52fe48009251416c750acaa7',
   'gender': 0,
   'id': 1207249,
   'name': 'Kyla Warren',
   'order': 31},
  {'cast_id': 53,
   'character': 'Troupe',
   'credit_id': '52fe48009251416c750acaab',
   'gender': 0,
   'id': 1207250,
   'name': 'Lisa Roumain',
   'order': 32},
  {'cast_id': 54,
   'character': 'Troupe',
   'credit_id': '52fe48009251416c750acaaf',
   'gender': 1,
   'id': 83105,
   'name': 'Debra Wilson',
   'order': 33},
  {'cast_id': 57,
   'character': 'Troupe',
   'credit_id': '52fe48009251416c750acabb',
   'gender': 0,
   'id': 1207253,
   'name': 'Chris Mala',
   'order': 34},
  {'cast_id': 55,
   'character': 'Troupe',
   'credit_id': '52fe48009251416c750acab3',
   'gender': 0,
   'id': 1207251,
   'name': 'Taylor Kibby',
   'order': 35},
  {'cast_id': 56,
   'character': 'Troupe',
   'credit_id': '52fe48009251416c750acab7',
   'gender': 0,
   'id': 1207252,
   'name': 'Jodie Landau',
   'order': 36},
  {'cast_id': 58,
   'character': 'Troupe',
   'credit_id': '52fe48009251416c750acabf',
   'gender': 0,
   'id': 1207254,
   'name': 'Julie Lamm',
   'order': 37},
  {'cast_id': 59,
   'character': 'Troupe',
   'credit_id': '52fe48009251416c750acac3',
   'gender': 0,
   'id': 1207257,
   'name': 'Cullen B. Madden',
   'order': 38},
  {'cast_id': 60,
   'character': 'Troupe',
   'credit_id': '52fe48009251416c750acac7',
   'gender': 0,
   'id': 1207259,
   'name': 'Joseph Brady Madden',
   'order': 39},
  {'cast_id': 61,
   'character': 'Troupe',
   'credit_id': '52fe48009251416c750acacb',
   'gender': 0,
   'id': 1207262,
   'name': 'Frankie Torres',
   'order': 40},
  {'cast_id': 62,
   'character': 'Troupe',
   'credit_id': '52fe48009251416c750acacf',
   'gender': 1,
   'id': 1158600,
   'name': 'Austin Wilson',
   'order': 41},
  {'cast_id': 63,
   'character': 'Troupe',
   'credit_id': '52fe48019251416c750acad3',
   'gender': 1,
   'id': 983705,
   'name': 'Sara Wilson',
   'order': 42},
  {'cast_id': 64,
   'character': 'Troupe',
   'credit_id': '52fe48019251416c750acad7',
   'gender': 0,
   'id': 1207263,
   'name': 'Tamica Washington-Miller',
   'order': 43},
  {'cast_id': 65,
   'character': 'Op Center Staff',
   'credit_id': '52fe48019251416c750acadb',
   'gender': 1,
   'id': 1145098,
   'name': 'Lucy Briant',
   'order': 44},
  {'cast_id': 66,
   'character': 'Op Center Staff',
   'credit_id': '52fe48019251416c750acadf',
   'gender': 2,
   'id': 33305,
   'name': 'Nathan Meister',
   'order': 45},
  {'cast_id': 67,
   'character': 'Op Center Staff',
   'credit_id': '52fe48019251416c750acae3',
   'gender': 0,
   'id': 1207264,
   'name': 'Gerry Blair',
   'order': 46},
  {'cast_id': 68,
   'character': 'Op Center Staff',
   'credit_id': '52fe48019251416c750acae7',
   'gender': 2,
   'id': 33311,
   'name': 'Matthew Chamberlain',
   'order': 47},
  {'cast_id': 69,
   'character': 'Op Center Staff',
   'credit_id': '52fe48019251416c750acaeb',
   'gender': 0,
   'id': 1207265,
   'name': 'Paul Yates',
   'order': 48},
  {'cast_id': 70,
   'character': 'Op Center Duty Officer',
   'credit_id': '52fe48019251416c750acaef',
   'gender': 0,
   'id': 1207266,
   'name': 'Wray Wilson',
   'order': 49},
  {'cast_id': 71,
   'character': 'Op Center Staff',
   'credit_id': '52fe48019251416c750acaf3',
   'gender': 2,
   'id': 54492,
   'name': 'James Gaylyn',
   'order': 50},
  {'cast_id': 72,
   'character': 'Dancer',
   'credit_id': '52fe48019251416c750acaf7',
   'gender': 0,
   'id': 1207267,
   'name': 'Melvin Leno Clark III',
   'order': 51},
  {'cast_id': 73,
   'character': 'Dancer',
   'credit_id': '52fe48019251416c750acafb',
   'gender': 0,
   'id': 1207268,
   'name': 'Carvon Futrell',
   'order': 52},
  {'cast_id': 74,
   'character': 'Dancer',
   'credit_id': '52fe48019251416c750acaff',
   'gender': 0,
   'id': 1207269,
   'name': 'Brandon Jelkes',
   'order': 53},
  {'cast_id': 75,
   'character': 'Dancer',
   'credit_id': '52fe48019251416c750acb03',
   'gender': 0,
   'id': 1207270,
   'name': 'Micah Moch',
   'order': 54},
  {'cast_id': 76,
   'character': 'Dancer',
   'credit_id': '52fe48019251416c750acb07',
   'gender': 0,
   'id': 1207271,
   'name': 'Hanniyah Muhammad',
   'order': 55},
  {'cast_id': 77,
   'character': 'Dancer',
   'credit_id': '52fe48019251416c750acb0b',
   'gender': 0,
   'id': 1207272,
   'name': 'Christopher Nolen',
   'order': 56},
  {'cast_id': 78,
   'character': 'Dancer',
   'credit_id': '52fe48019251416c750acb0f',
   'gender': 0,
   'id': 1207273,
   'name': 'Christa Oliver',
   'order': 57},
  {'cast_id': 79,
   'character': 'Dancer',
   'credit_id': '52fe48019251416c750acb13',
   'gender': 0,
   'id': 1207274,
   'name': 'April Marie Thomas',
   'order': 58},
  {'cast_id': 80,
   'character': 'Dancer',
   'credit_id': '52fe48019251416c750acb17',
   'gender': 0,
   'id': 1207275,
   'name': 'Bravita A. Threatt',
   'order': 59},
  {'cast_id': 81,
   'character': 'Mining Chief (uncredited)',
   'credit_id': '52fe48019251416c750acb1b',
   'gender': 0,
   'id': 1207276,
   'name': 'Colin Bleasdale',
   'order': 60},
  {'cast_id': 82,
   'character': 'Veteran Miner (uncredited)',
   'credit_id': '52fe48019251416c750acb1f',
   'gender': 0,
   'id': 107969,
   'name': 'Mike Bodnar',
   'order': 61},
  {'cast_id': 83,
   'character': 'Richard (uncredited)',
   'credit_id': '52fe48019251416c750acb23',
   'gender': 0,
   'id': 1207278,
   'name': 'Matt Clayton',
   'order': 62},
  {'cast_id': 84,
   'character': "Nav'i (uncredited)",
   'credit_id': '52fe48019251416c750acb27',
   'gender': 1,
   'id': 147898,
   'name': 'Nicole Dionne',
   'order': 63},
  {'cast_id': 85,
   'character': 'Trooper (uncredited)',
   'credit_id': '52fe48019251416c750acb2b',
   'gender': 0,
   'id': 1207280,
   'name': 'Jamie Harrison',
   'order': 64},
  {'cast_id': 86,
   'character': 'Trooper (uncredited)',
   'credit_id': '52fe48019251416c750acb2f',
   'gender': 0,
   'id': 1207281,
   'name': 'Allan Henry',
   'order': 65},
  {'cast_id': 87,
   'character': 'Ground Technician (uncredited)',
   'credit_id': '52fe48019251416c750acb33',
   'gender': 2,
   'id': 1207282,
   'name': 'Anthony Ingruber',
   'order': 66},
  {'cast_id': 88,
   'character': 'Flight Crew Mechanic (uncredited)',
   'credit_id': '52fe48019251416c750acb37',
   'gender': 0,
   'id': 1207283,
   'name': 'Ashley Jeffery',
   'order': 67},
  {'cast_id': 14,
   'character': 'Samson Pilot',
   'credit_id': '52fe48009251416c750ac9f9',
   'gender': 0,
   'id': 98216,
   'name': 'Dean Knowsley',
   'order': 68},
  {'cast_id': 89,
   'character': 'Trooper (uncredited)',
   'credit_id': '52fe48019251416c750acb3b',
   'gender': 0,
   'id': 1201399,
   'name': 'Joseph Mika-Hunt',
   'order': 69},
  {'cast_id': 90,
   'character': 'Banshee (uncredited)',
   'credit_id': '52fe48019251416c750acb3f',
   'gender': 0,
   'id': 236696,
   'name': 'Terry Notary',
   'order': 70},
  {'cast_id': 91,
   'character': 'Soldier (uncredited)',
   'credit_id': '52fe48019251416c750acb43',
   'gender': 0,
   'id': 1207287,
   'name': 'Kai Pantano',
   'order': 71},
  {'cast_id': 92,
   'character': 'Blast Technician (uncredited)',
   'credit_id': '52fe48019251416c750acb47',
   'gender': 0,
   'id': 1207288,
   'name': 'Logan Pithyou',
   'order': 72},
  {'cast_id': 93,
   'character': 'Vindum Raah (uncredited)',
   'credit_id': '52fe48019251416c750acb4b',
   'gender': 0,
   'id': 1207289,
   'name': 'Stuart Pollock',
   'order': 73},
  {'cast_id': 94,
   'character': 'Hero (uncredited)',
   'credit_id': '52fe48019251416c750acb4f',
   'gender': 0,
   'id': 584868,
   'name': 'Raja',
   'order': 74},
  {'cast_id': 95,
   'character': 'Ops Centreworker (uncredited)',
   'credit_id': '52fe48019251416c750acb53',
   'gender': 0,
   'id': 1207290,
   'name': 'Gareth Ruck',
   'order': 75},
  {'cast_id': 96,
   'character': 'Engineer (uncredited)',
   'credit_id': '52fe48019251416c750acb57',
   'gender': 0,
   'id': 1062463,
   'name': 'Rhian Sheehan',
   'order': 76},
  {'cast_id': 97,
   'character': "Col. Quaritch's Mech Suit (uncredited)",
   'credit_id': '52fe48019251416c750acb5b',
   'gender': 0,
   'id': 60656,
   'name': 'T. J. Storm',
   'order': 77},
  {'cast_id': 98,
   'character': 'Female Marine (uncredited)',
   'credit_id': '52fe48019251416c750acb5f',
   'gender': 0,
   'id': 1207291,
   'name': 'Jodie Taylor',
   'order': 78},
  {'cast_id': 99,
   'character': 'Ikran Clan Leader (uncredited)',
   'credit_id': '52fe48019251416c750acb63',
   'gender': 1,
   'id': 1186027,
   'name': 'Alicia Vela-Bailey',
   'order': 79},
  {'cast_id': 100,
   'character': 'Geologist (uncredited)',
   'credit_id': '52fe48019251416c750acb67',
   'gender': 0,
   'id': 1207292,
   'name': 'Richard Whiteside',
   'order': 80},
  {'cast_id': 101,
   'character': "Na'vi (uncredited)",
   'credit_id': '52fe48019251416c750acb6b',
   'gender': 0,
   'id': 103259,
   'name': 'Nikie Zambo',
   'order': 81},
  {'cast_id': 102,
   'character': 'Ambient Room Tech / Troupe',
   'credit_id': '52fe48019251416c750acb6f',
   'gender': 1,
   'id': 42286,
   'name': 'Julene Renee',
   'order': 82}],
 'crew': [{'credit_id': '52fe48009251416c750aca23',
   'department': 'Editing',
   'gender': 0,
   'id': 1721,
   'job': 'Editor',
   'name': 'Stephen E. Rivkin'},
  {'credit_id': '539c47ecc3a36810e3001f87',
   'department': 'Art',
   'gender': 2,
   'id': 496,
   'job': 'Production Design',
   'name': 'Rick Carter'},
  {'credit_id': '54491c89c3a3680fb4001cf7',
   'department': 'Sound',
   'gender': 0,
   'id': 900,
   'job': 'Sound Designer',
   'name': 'Christopher Boyes'},
  {'credit_id': '54491cb70e0a267480001bd0',
   'department': 'Sound',
   'gender': 0,
   'id': 900,
   'job': 'Supervising Sound Editor',
   'name': 'Christopher Boyes'},
  {'credit_id': '539c4a4cc3a36810c9002101',
   'department': 'Production',
   'gender': 1,
   'id': 1262,
   'job': 'Casting',
   'name': 'Mali Finn'},
  {'credit_id': '5544ee3b925141499f0008fc',
   'department': 'Sound',
   'gender': 2,
   'id': 1729,
   'job': 'Original Music Composer',
   'name': 'James Horner'},
  {'credit_id': '52fe48009251416c750ac9c3',
   'department': 'Directing',
   'gender': 2,
   'id': 2710,
   'job': 'Director',
   'name': 'James Cameron'},
  {'credit_id': '52fe48009251416c750ac9d9',
   'department': 'Writing',
   'gender': 2,
   'id': 2710,
   'job': 'Writer',
   'name': 'James Cameron'},
  {'credit_id': '52fe48009251416c750aca17',
   'department': 'Editing',
   'gender': 2,
   'id': 2710,
   'job': 'Editor',
   'name': 'James Cameron'},
  {'credit_id': '52fe48009251416c750aca29',
   'department': 'Production',
   'gender': 2,
   'id': 2710,
   'job': 'Producer',
   'name': 'James Cameron'},
  {'credit_id': '52fe48009251416c750aca3f',
   'department': 'Writing',
   'gender': 2,
   'id': 2710,
   'job': 'Screenplay',
   'name': 'James Cameron'},
  {'credit_id': '539c4987c3a36810ba0021a4',
   'department': 'Art',
   'gender': 2,
   'id': 7236,
   'job': 'Art Direction',
   'name': 'Andrew Menzies'},
  {'credit_id': '549598c3c3a3686ae9004383',
   'department': 'Visual Effects',
   'gender': 0,
   'id': 6690,
   'job': 'Visual Effects Producer',
   'name': 'Jill Brooks'},
  {'credit_id': '52fe48009251416c750aca4b',
   'department': 'Production',
   'gender': 1,
   'id': 6347,
   'job': 'Casting',
   'name': 'Margery Simkin'},
  {'credit_id': '570b6f419251417da70032fe',
   'department': 'Art',
   'gender': 2,
   'id': 6878,
   'job': 'Supervising Art Director',
   'name': 'Kevin Ishioka'},
  {'credit_id': '5495a0fac3a3686ae9004468',
   'department': 'Sound',
   'gender': 0,
   'id': 6883,
   'job': 'Music Editor',
   'name': 'Dick Bernstein'},
  {'credit_id': '54959706c3a3686af3003e81',
   'department': 'Sound',
   'gender': 0,
   'id': 8159,
   'job': 'Sound Effects Editor',
   'name': 'Shannon Mills'},
  {'credit_id': '54491d58c3a3680fb1001ccb',
   'department': 'Sound',
   'gender': 0,
   'id': 8160,
   'job': 'Foley',
   'name': 'Dennie Thorpe'},
  {'credit_id': '54491d6cc3a3680fa5001b2c',
   'department': 'Sound',
   'gender': 0,
   'id': 8163,
   'job': 'Foley',
   'name': 'Jana Vance'},
  {'credit_id': '52fe48009251416c750aca57',
   'department': 'Costume & Make-Up',
   'gender': 1,
   'id': 8527,
   'job': 'Costume Design',
   'name': 'Deborah Lynn Scott'},
  {'credit_id': '52fe48009251416c750aca2f',
   'department': 'Production',
   'gender': 2,
   'id': 8529,
   'job': 'Producer',
   'name': 'Jon Landau'},
  {'credit_id': '539c4937c3a36810ba002194',
   'department': 'Art',
   'gender': 0,
   'id': 9618,
   'job': 'Art Direction',
   'name': 'Sean Haworth'},
  {'credit_id': '539c49b6c3a36810c10020e6',
   'department': 'Art',
   'gender': 1,
   'id': 12653,
   'job': 'Set Decoration',
   'name': 'Kim Sinclair'},
  {'credit_id': '570b6f2f9251413a0e00020d',
   'department': 'Art',
   'gender': 1,
   'id': 12653,
   'job': 'Supervising Art Director',
   'name': 'Kim Sinclair'},
  {'credit_id': '54491a6c0e0a26748c001b19',
   'department': 'Art',
   'gender': 2,
   'id': 14350,
   'job': 'Set Designer',
   'name': 'Richard F. Mays'},
  {'credit_id': '56928cf4c3a3684cff0025c4',
   'department': 'Production',
   'gender': 1,
   'id': 20294,
   'job': 'Executive Producer',
   'name': 'Laeta Kalogridis'},
  {'credit_id': '52fe48009251416c750aca51',
   'department': 'Costume & Make-Up',
   'gender': 0,
   'id': 17675,
   'job': 'Costume Design',
   'name': 'Mayes C. Rubeo'},
  {'credit_id': '52fe48009251416c750aca11',
   'department': 'Camera',
   'gender': 2,
   'id': 18265,
   'job': 'Director of Photography',
   'name': 'Mauro Fiore'},
  {'credit_id': '5449194d0e0a26748f001b39',
   'department': 'Art',
   'gender': 0,
   'id': 42281,
   'job': 'Set Designer',
   'name': 'Scott Herbertson'},
  {'credit_id': '52fe48009251416c750aca05',
   'department': 'Crew',
   'gender': 0,
   'id': 42288,
   'job': 'Stunts',
   'name': 'Woody Schultz'},
  {'credit_id': '5592aefb92514152de0010f5',
   'department': 'Costume & Make-Up',
   'gender': 0,
   'id': 29067,
   'job': 'Makeup Artist',
   'name': 'Linda DeVetta'},
  {'credit_id': '5592afa492514152de00112c',
   'department': 'Costume & Make-Up',
   'gender': 0,
   'id': 29067,
   'job': 'Hairstylist',
   'name': 'Linda DeVetta'},
  {'credit_id': '54959ed592514130fc002e5d',
   'department': 'Camera',
   'gender': 2,
   'id': 33302,
   'job': 'Camera Operator',
   'name': 'Richard Bluck'},
  {'credit_id': '539c4891c3a36810ba002147',
   'department': 'Art',

In [50]:
c1.keys()

dict_keys(['movie_id', 'title', 'cast', 'crew'])

In [55]:
credits_query = """
MERGE (m:Movie {id: $movie_id})

with m, $cast AS cast
UNWIND cast AS c
    MERGE (p:Person {id: c.id})
    ON CREATE SET 
        p.name = c.name,
        p.gender = c.gender

    MERGE (p)-[casted:CASTED_IN {credit_id: c.credit_id}]->(m)
    ON CREATE SET 
        casted.character = c.character

WITH m, $crew AS crew
UNWIND crew AS cr
    MERGE (p1:Person {id: cr.id})
    ON CREATE SET 
        p1.name = cr.name,
        p1.gender = cr.gender
    
    MERGE (p1)-[work:WORKED_IN {credit_id: cr.credit_id}]->(m)
    ON CREATE SET
        work.department = cr.department,
        work.job = cr.job
        
RETURN m
"""

run_query(credits_query, c1)

[{'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,
   'homepage': 'http://www.avatarmovie.com/',
   'budget': 237000000,
   'status': 'Released'}},
 {'m': {'overview': 'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.',
   'original_language': 'en',
   'original_title': 'Avatar',
   'title': 'Avatar',
   'revenue': 2787965087,
   'release_date': neo4j.time.DateTime(2009, 12, 10, 0, 0, 0, 0),
   'popularity': 150.437577,
   'vote_average': 7.2,
   'tagline': 'Enter the World of Pandora.',
   'id': 19995,
   'vote_count': 11800,

In [7]:
credits_json_tables = defaultdict(list)

for index, row in df_credits.iterrows():
    for c in json_columns:
        credits_json_tables[c].extend(row[c])
for key, items in credits_json_tables.items():
    print(f"{key}: {len(items)} items")
    credits_json_tables[key] = pd.DataFrame(items).drop_duplicates().reset_index(drop=True)
    print(f"{key}: {credits_json_tables[key].shape}")
    display(credits_json_tables[key].head())

cast: 106257 items
cast: (106257, 7)

,cast_id,character,credit_id,gender,id,name,order
0,242,Jake Sully,5602a8a7c3a3685532001c9a,2,65731,Sam Worthington,0
1,3,Neytiri,52fe48009251416c750ac9cb,1,8691,Zoe Saldana,1
2,25,Dr. Grace Augustine,52fe48009251416c750aca39,1,10205,Sigourney Weaver,2
3,4,Col. Quaritch,52fe48009251416c750ac9cf,2,32747,Stephen Lang,3
4,5,Trudy Chacon,52fe48009251416c750ac9d3,1,17647,Michelle Rodriguez,4

crew: 129581 items
crew: (129581, 6)

,credit_id,department,gender,id,job,name
0,52fe48009251416c750aca23,Editing,0,1721,Editor,Stephen E. Rivkin
1,539c47ecc3a36810e3001f87,Art,2,496,Production Design,Rick Carter
2,54491c89c3a3680fb4001cf7,Sound,0,900,Sound Designer,Christopher Boyes
3,54491cb70e0a267480001bd0,Sound,0,900,Supervising Sound Editor,Christopher Boyes
4,539c4a4cc3a36810c9002101,Production,1,1262,Casting,Mali Finn

In [41]:
credits_json_tables['cast'].sort_values('cast_id')

,cast_id,character,credit_id,gender,id,name,order
89245,0,Annie Dwyer,5432022c0e0a265872003257,1,25703,Lake Bell,1
96528,0,Samantha,54cf6d8ec3a3687f940081e1,1,23931,Mira Sorvino,1
89291,0,Christian,55c13ce29251410f2a003096,2,9562,Marlon Wayans,0
28622,0,James 'Whitey' Bulger,5330579ec3a3685fbb006b13,2,85,Johnny Depp,0
77159,0,Eilis Lacey,53d14a2e0e0a265e0100cd01,1,36592,Saoirse Ronan,0
...,...,...,...,...,...,...,...
84635,1115,Go-Go Dancer,58d9374b925141448e027198,1,1784680,Makenzi Swicegood,79
84636,1116,Penelope,58d937d0c3a368123406d0ca,1,1784681,Jennifer Thompson,80
84637,1117,Beach Party Girl,58d938099251411f90070cf9,1,1784682,Rachael Thompson,81
84638,1118,Party Girl,58d93890925141448e0272d0,1,1784683,Victoria Vodar,82
84639,1119,Beach Guy,58d93926c3a368127c06c536,0,1309904,Kenny Waymack Jr.,83

In [104]:
(credits_json_tables['cast'][credits_json_tables['cast']["id"] == 1])

,cast_id,character,credit_id,gender,id,name,order
9437,78,Baron Papanoida,584a4128c3a368141f01b620,2,1,George Lucas,24
19626,51,Man Kissing on Bridge (uncredited),5781e003c3a3681f4d000f21,2,1,George Lucas,27
30787,5,Disappointed Man,52fe4235c3a36847f800c2f7,2,1,George Lucas,21
49086,88,Missionary (uncredited),5895b352c3a36822e0004ad5,2,1,George Lucas,66

In [16]:
credits_json_tables['cast'][["id", "name"]].value_counts().sort_values(ascending=False).head(10)

id    name
2231  Samuel L. Jackson    67
380   Robert De Niro       57
62    Bruce Willis         51
1892  Matt Damon           48
192   Morgan Freeman       46
884   Steve Buscemi        43
3896  Liam Neeson          41
85    Johnny Depp          40
887   Owen Wilson          40
2963  Nicolas Cage         39
Name: count, dtype: int64

In [43]:
credits_json_tables['crew'][credits_json_tables['crew']["id"] == 1]

,credit_id,department,gender,id,job,name
3872,52fe4227c3a36847f800847d,Production,2,1,Executive Producer,George Lucas
3873,52fe4228c3a36847f80084c7,Writing,2,1,Story,George Lucas
3874,52fe4228c3a36847f80084cd,Writing,2,1,Characters,George Lucas
15097,52fe431fc3a36847f803bea3,Writing,2,1,Screenplay,George Lucas
15098,52fe431fc3a36847f803be97,Directing,2,1,Director,George Lucas
15099,52fe431fc3a36847f803bec1,Production,2,1,Executive Producer,George Lucas
15112,52fe431fc3a36847f803bd8b,Directing,2,1,Director,George Lucas
15113,52fe431fc3a36847f803bd91,Production,2,1,Producer,George Lucas
15114,52fe431fc3a36847f803bda3,Writing,2,1,Screenplay,George Lucas
15456,52fe431ec3a36847f803bca3,Writing,2,1,Screenplay,George Lucas
15457,52fe431ec3a36847f803bca9,Directing,2,1,Director,George Lucas
15458,52fe431ec3a36847f803bd03,Production,2,1,Executive Producer,George Lucas
51976,52fe4216c3a36847f8002e01,Production,2,1,Executive Producer,George Lucas
51977,52fe4216c3a36847f8002e69,Editing,2,1,Editor,George Lucas
51978,52fe4216c3a36847f8002e93,Writing,2,1,Characters,George Lucas
66680,52fe431ec3a36847f803bc0f,Writing,2,1,Screenplay,George Lucas
66681,52fe431ec3a36847f803bc53,Production,2,1,Executive Producer,George Lucas
66682,52fe431ec3a36847f803bc4d,Writing,2,1,Story,George Lucas
71557,52fe439d9251416c7501758b,Production,2,1,Executive Producer,George Lucas
72818,52fe4215c3a36847f8002c45,Production,2,1,Executive Producer,George Lucas
72819,52fe4215c3a36847f8002c7b,Editing,2,1,Editor,George Lucas
72820,5895b3a69251412e1400835b,Writing,2,1,Story,George Lucas
72821,5895b3b89251412e16008b8d,Writing,2,1,Characters,George Lucas
74608,588a748cc3a368409301c92a,Crew,2,1,Thanks,George Lucas
80765,566e19f292514169e200d46f,Editing,2,1,Editor,George Lucas
80766,52fe431ec3a36847f803bbcb,Production,2,1,Executive Producer,George Lucas
80767,52fe431ec3a36847f803bbc5,Writing,2,1,Story,George Lucas
83502,52fe4215c3a36847f8002a3d,Production,2,1,Executive Producer,George Lucas
83503,52fe4215c3a36847f8002a5b,Editing,2,1,Editor,George Lucas
83504,58959632c3a36822e0003388,Writing,2,1,Story,George Lucas
100147,52fe44be9251416c7503f5ed,Production,2,1,Executive Producer,George Lucas
102290,52fe420dc3a36847f8000437,Directing,2,1,Director,George Lucas
102291,52fe420dc3a36847f800045b,Production,2,1,Executive Producer,George Lucas
102292,562e75309251414006009955,Writing,2,1,Writer,George Lucas
107311,562ed26cc3a3681b4d00d676,Crew,2,1,Thanks,George Lucas
107944,56afb1ffc3a36831720007cb,Writing,2,1,Writer,George Lucas
126843,52fe427ec3a36847f80232b7,Writing,2,1,Screenplay,George Lucas
126844,52fe427ec3a36847f80232b1,Directing,2,1,Director,George Lucas

In [38]:
credits_json_tables['cast']["cast_id"].value_counts()

cast_id
4       2778
3       2617
5       2562
6       2387
13      2317
        ...
1115       1
1116       1
1117       1
1118       1
1119       1
Name: count, Length: 524, dtype: int64

In [42]:
pd.DataFrame(df_credits.loc[0, "crew"])

,credit_id,department,gender,id,job,name
0,52fe48009251416c750aca23,Editing,0,1721,Editor,Stephen E. Rivkin
1,539c47ecc3a36810e3001f87,Art,2,496,Production Design,Rick Carter
2,54491c89c3a3680fb4001cf7,Sound,0,900,Sound Designer,Christopher Boyes
3,54491cb70e0a267480001bd0,Sound,0,900,Supervising Sound Editor,Christopher Boyes
4,539c4a4cc3a36810c9002101,Production,1,1262,Casting,Mali Finn
...,...,...,...,...,...,...
148,5592b2c3c3a36869e800003c,Crew,0,1483231,CG Supervisor,Philippe Rebours
149,5592b317c3a36877470012af,Crew,0,1483232,CG Supervisor,Michael Takarangi
150,5592b345c3a36877470012bb,Crew,0,1483233,CG Supervisor,David Weitzberg
151,5592b37cc3a368775100113b,Crew,0,1483234,CG Supervisor,Ben White
152,573c8e2f9251413f5d000094,Crew,1,1621932,Stunts,Min Windle

In [36]:
credits_json_tables["cast"]["gender"].value_counts()

gender
2    48291
0    33798
1    24168
Name: count, dtype: int64

In [57]:
# load neo4j credentials file
from dotenv import dotenv_values
config = dotenv_values("Neo4j Aura Created Nov 24 2025.txt")
config

OrderedDict([('NEO4J_URI', 'neo4j+s://e8504d2b.databases.neo4j.io'),
             ('NEO4J_USERNAME', 'neo4j'),
             ('NEO4J_PASSWORD', 'X0AvacVMtCQGNHiGGgbmyXC1f5AkIURKIG7NkHgYqHs'),
             ('NEO4J_DATABASE', 'neo4j'),
             ('AURA_INSTANCEID', 'e8504d2b'),
             ('AURA_INSTANCENAME', 'IF5150_Movie Recommender')])